// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://baidgzdxvoxcdmlupeii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhaWRnemR4dm94Y2RtbHVwZWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTA5NDksImV4cCI6MjA3NzEyNjk0OX0.qVuvbE5OouyzsCU8hG1sYQ4K6aEhbt_Zj1cfZwfZysM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);